# Generated by Django 5.1.15 on 2026-09-27 13:15

import apps.orders.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, default=apps.orders.models._generate_short_code, max_length=16, unique=True, verbose_name='Номер')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Имя гостя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Черновик'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('handed_off', 'Отдан'), ('cancelled', 'Отменён')], default='new', max_length=16, verbose_name='Статус')),
                ('fulfilment', models.CharField(choices=[('here', 'В зале'), ('to_go', 'С собой')], default='here', max_length=8, verbose_name='Формат')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итого, ₽')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен в')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Готов в')),
                ('handed_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Отдан в')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу, ₽')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderLineModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('price_delta_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Изменение цены (снимок), ₽')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderline', verbose_name='Позиция')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.modifier', verbose_name='Модификатор')),
            ],
            options={
                'verbose_name': 'Модификатор позиции',
                'verbose_name_plural': 'Модификаторы позиции',
            },
        ),
    ]
