# Generated by Django 5.1.15 on 2026-10-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заметка к позиции'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, verbose_name='Дата смены')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='Открыта')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Открыта в')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта в')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_closed', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_opened', to=settings.AUTH_USER_MODEL, verbose_name='Открыл')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-business_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Заполняется при оплате или отправке в очередь, если смена открыта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shift', verbose_name='Смена'),
        ),
    ]
