# Generated by Django 5.1.15 on 2026-10-07 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shift_cashier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 30), help_text='Время, которое кассир вписал при открытии. К нему прибавляется прошедшее с открытия смены.', verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='Часы сервера в момент открытия. Для времени заказов берётся только разница с этим моментом, само значение не показывается.', null=True, verbose_name='Открыта в'),
        ),
    ]
