# Generated by Django 5.1.15 on 2026-09-27 13:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Выручка, ₽')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Заказов')),
                ('paid_orders', models.PositiveIntegerField(default=0, verbose_name='Оплаченных')),
                ('unpaid_orders', models.PositiveIntegerField(default=0, verbose_name='Не оплаченных')),
                ('avg_check', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Средний чек, ₽')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Закрыто')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
            ],
            options={
                'verbose_name': 'Дневная сводка',
                'verbose_name_plural': 'Дневные сводки',
                'ordering': ('-date',),
            },
        ),
    ]
