# Generated by Django 5.1.15 on 2026-09-27 13:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('color', models.CharField(default='#f2b134', help_text='HEX-цвет для оформления вкладки, например #f2b134.', max_length=16, verbose_name='Цвет плитки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('selection_mode', models.CharField(choices=[('single', 'Один вариант'), ('multi', 'Несколько вариантов')], default='multi', max_length=10, verbose_name='Режим выбора')),
                ('is_required', models.BooleanField(default=False, help_text='Кассир обязан выбрать хотя бы одну опцию.', verbose_name='Обязателен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа модификаторов',
                'verbose_name_plural': 'Группы модификаторов',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Может быть отрицательным (скидка).', max_digits=8, verbose_name='Изменение цены, ₽')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Модификаторы',
                'ordering': ('group', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Цена, ₽')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('modifier_groups', models.ManyToManyField(blank=True, help_text='Какие опции показывать при добавлении в заказ.', related_name='products', to='catalog.modifiergroup', verbose_name='Группы модификаторов')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('category__order', 'order', 'name'),
            },
        ),
    ]
