# Generated by Django 5.1.15 on 2026-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Для группы одного выбора: чип уже нажат, когда открывается шторка допов.', verbose_name='Выбран по умолчанию'),
        ),
    ]
