# Generated by Django 5.1.15 on 2026-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_kassa_addons_and_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiergroup',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
